[package]
name = "flappy_bevy"
version = "0.1.0"
edition.workspace = true

[dependencies]

bevy = {git = "https://github.com/bevyengine/bevy.git", features = ["wayland", "dynamic_linking"]}
rand = "*"
