[package]
name = "mini_apps"
version = "0.1.0"
# edition.workspace = true
edition = "2024"

[dependencies]

bevy = {git = "https://github.com/bevyengine/bevy.git", features = ["wayland"]}
image.workspace = true
rand = "0.8.5"
serde = "1.0.210"
serde_json = "1.0.128"
